### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Xchos** [Vibuf/searchbar#1]
![image](https://user-images.githubusercontent.com/2938356/35387041-8f1ba8ca-01ce-11e8-8c1f-3b20eeca6f7e.png)
Styly mohou být v jednom objektu

tj
```javascript
const styles = {
    input: {
       // ...
    },
    container: {
      // ...
    }
}
```
pak je možné tyto styly aplikovat skrz `styles.input` či `styles.container` .. 

**Coding Conventions**
`this.Handle.bind(this)` není zapotřebí bind, jelikož `Handle` je fat arrow function. Postačí `this.Handle`
Dále by bylo hezké aby se funkce jmenovala nějak srozumitelně. To je např `handleInputField`. Všimněte si prvního znaku malého. Coding Conventions nám říkají, že je dobré používat Lower-CamelCase. to je každé slovo které by mělo být oddělené mezerou by mělo začínat velkým písmenem. U prvního slova je první písmeno malé. `exampleOfLowerCamelCase`.
Název třídy by měl být Upper-CamelCase (chcete-li PascalCase). Tedy třída se bude jmenovat `SearchBar` nikoliv `searchbar`
Více se dočtete [zde](https://www.w3schools.com/js/js_conventions.asp)

**destrukturalizace**
Pokud víte, že budete využívat nějakou proměnnou vícekrát, např `this.state.sentence` je vhodné si tento objekt (`this.state`) destrukturalizovat. Zpřehlední to kód, jelikož využívání sentence je potom daleko čitelnější. Na začátku render funkce použijte `const { sentence } = this.state;` Potom lze na místo `this.state.sentence` využívat pouze `sentence`.

**Po úpravách**
![image](https://user-images.githubusercontent.com/2938356/35387801-80ad5790-01d1-11e8-9f26-bd4c331c69c5.png)

**Comment by Vibuf** [comment]
Kod je upraven takto: 
import React, { Component } from 'react';

export default class SearchBar extends Component {

    state = { sentence: '' }

    handleFieldText = (e) => this.setState({ sentence: e.target.value.trimLeft() })

    render() {
        const style = {
            input: {
                height: 200,
                width: '100%',
                fontSize: 50,
            },
            mainDiv: {
                textAlign: 'center'
            }
        }
        const {sentence} = this.state;
        return (
            <div style={style.mainDiv}>

                <input placeholder="write text" style={style.input} value={sentence} onChange={this.handleFieldText} />

                Váš text:<p style={style.input}> {sentence.toLocaleUpperCase()} </p>
            </div>
        )
    }
};
